
env:
   global:
     - CONAN_REFERENCE: "Botan/2.1.0"
     - CONAN_USERNAME: "fmorgner"
     - CONAN_LOGIN_USERNAME: "fmorgner"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/fmorgner/conan-fmorgner"
     - CONAN_TOTAL_PAGES: 2

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.8 CONAN_DOCKER_IMAGE=lasote/conanclang38 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.8 CONAN_DOCKER_IMAGE=lasote/conanclang38 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE="Debug"
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE="Release"
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE="Debug"
#      - <<: *osx
#        osx_image: xcode7.3
#        env: CONAN_APPLE_CLANG_VERSIONS=7.3
#      - <<: *osx
#        osx_image: xcode8.2
#        env: CONAN_APPLE_CLANG_VERSIONS=8.0
#      - <<: *osx
#        osx_image: xcode8.3
#        env: CONAN_APPLE_CLANG_VERSIONS=8.1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
