build: false

environment:
    PYTHON: "C:\\Python35"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "Asio/1.10.8"
    CONAN_USERNAME: "fmorgner"
    CONAN_LOGIN_USERNAME: "fmorgner"
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/fmorgner/conan-fmorgner"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user

test_script:
  - python build.py
